version: 2

sources:
  - name: raw_jolpica
    database: raw_jolpica
    schema: raw_jolpica
    tables:
      - name: seasons
      - name: circuits
      - name: constructors
      - name: drivers
      - name: races
        loaded_at_field: _ingested_at
        freshness:
          warn_after: {count: 20, period: day}
          error_after: {count: 40, period: day}
      - name: results
        loaded_at_field: _ingested_at
        freshness:
          warn_after: {count: 20, period: day}
          error_after: {count: 40, period: day}
      - name: qualifying
        loaded_at_field: _ingested_at
        freshness:
          warn_after: {count: 20, period: day}
          error_after: {count: 40, period: day}
      - name: sprint_results
      - name: lap_times
      - name: pit_stops
      - name: driver_standings
      - name: constructor_standings

  - name: raw_openf1
    database: raw_openf1
    schema: raw_openf1
    tables:
      - name: sessions
        loaded_at_field: _ingested_at
        freshness:
          warn_after: {count: 20, period: day}
          error_after: {count: 40, period: day}
        columns:
          - name: session_type
            tests:
              - accepted_values:
                  arguments:
                    values: ['Race', 'Qualifying', 'Sprint', 'Sprint Qualifying',
                             'Practice', 'Practice 1', 'Practice 2', 'Practice 3']
      - name: drivers
      - name: laps
        loaded_at_field: _ingested_at
        freshness:
          warn_after: {count: 20, period: day}
          error_after: {count: 40, period: day}
      - name: pit
      - name: stints
        loaded_at_field: _ingested_at
        freshness:
          warn_after: {count: 20, period: day}
          error_after: {count: 40, period: day}
      - name: intervals
      - name: weather
        loaded_at_field: _ingested_at
        freshness:
          warn_after: {count: 20, period: day}
          error_after: {count: 40, period: day}
      - name: race_control
      - name: car_data
        loaded_at_field: _ingested_at
        freshness:
          warn_after: {count: 20, period: day}
          error_after: {count: 40, period: day}
      - name: location
      - name: team_radio

  - name: raw_fastf1
    database: raw_fastf1
    schema: raw_fastf1
    tables:
      - name: car_telemetry
        loaded_at_field: _ingested_at
        freshness:
          warn_after: {count: 20, period: day}
          error_after: {count: 40, period: day}
